---
hosts:
  puppetmaster_domain: puppet,puppetmaster
  dbserver_domain: qaamysql,dbserver
  publisher_domain: pub.am.wso2.com,loadbalancer1
  store_domain: store.am.wso2.com,loadbalancer1
  keymanager_domain: keymanager.am.wso2.com,loadbalancer1
  gateway_domain: gateway.am.wso2.com,loadbalancer1
  gatewaymgt_domain: mgt.gateway.am.wso2.com,loadbalancer1

nodes:
  loadbalancer1: 192.168.57.250
  gateway1: 192.168.57.232
  gateway2: 192.168.57.231
  keymanager1: 192.168.57.227
  keymanager2: 192.168.57.225
  pubstore1: 192.168.57.228
  puppetmaster: 192.168.57.148
  dbserver: 192.168.57.233
